//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int BookingId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> AdultCount { get; set; }
        public Nullable<int> ChildCount { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual Hotels Hotel { get; set; }
        public virtual Customers Customer { get; set; }
        public virtual HotelRooms HotelRoom { get; set; }
    }
}
