//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictV10
    {
        public int DistrictId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> TownId { get; set; }
        public string DistrictName { get; set; }
    
        public virtual CountryV10 CountryV10 { get; set; }
        public virtual CountryV10 CountryV101 { get; set; }
        public virtual TownV10 TownV10 { get; set; }
    }
}
