//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelPropertyConnects
    {
        public int HotelPropertyConnectId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> HotelPropertyId { get; set; }
    
        public virtual Hotels Hotel { get; set; }
    }
}
