//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelBookingDBEntities : DbContext
    {
        public HotelBookingDBEntities()
            : base("name=HotelBookingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<HotelComments> HotelComments { get; set; }
        public virtual DbSet<HotelPropertyConnects> HotelPropertyConnects { get; set; }
        public virtual DbSet<HotelRooms> HotelRooms { get; set; }
        public virtual DbSet<RoomProperties> RoomProperties { get; set; }
        public virtual DbSet<RoomTypes> RoomTypes { get; set; }
        public virtual DbSet<HotelPhotos> HotelPhotos { get; set; }
        public virtual DbSet<RoomPropertyConnects> RoomPropertyConnects { get; set; }
        public virtual DbSet<Hotels> Hotels { get; set; }
        public virtual DbSet<HotelProperties> HotelProperties { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<CountryV10> CountryV10 { get; set; }
        public virtual DbSet<DistrictV10> DistrictV10 { get; set; }
        public virtual DbSet<TownV10> TownV10 { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
