//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTypes
    {
        public int RoomTypeId { get; set; }
        public string Title { get; set; }
        public Nullable<int> BedCount { get; set; }
        public Nullable<int> PersonCount { get; set; }
        public Nullable<bool> Rebate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    }
}
